// 全站单一数据源：下载链接、版本号、迴路链接
// Generated by Trae Work

const B = (p) => (import.meta.env.BASE_URL || '/') + p

export const APP = {
  vault: {
    name: 'Vault',
    icon: B('assets/icon-vault.svg'),
    tag: '保險箱 · 離線私鑰錨',
    version: 'v3.78.0',
    code: '41',
    url: 'https://github.com/eneatlnc-cell/Spark/releases/download/v3.78.1/Vault-3.78.0-release.apk',
    shy: '離線金鑰',
    blurb: '保管你的私鑰、為你的身分簽名——就在一台從物理上連不上網路的裝置上。',
    features: [
      ['無網路', '完全沒有任何 INTERNET 權限，金鑰封存在 Keystore TEE / DRM。'],
      ['零出口', '除非你核准一筆簽名，否則什麼都出不了這台裝置。'],
      ['為 Engine 簽名', '身分簽章透過已簽署的 IPC 回呼，跨裝置完成。']
    ],
    stats: [
      ['0', 'INTERNET 權限'],
      ['1', '機內私鑰'],
      ['0', '可達網路'],
      ['∞', '連續簽署審計']
    ],
    why: {
      kicker: '為何離線',
      title: ['攻破伺服器，只能拿走密文。', '資料外洩裡沒有金鑰。'],
      sub: '多數「加密」App 把路由與金鑰保管放在同一個信任區域。Vault 用最原始的方式結束這個賭局：持有金鑰的裝置，物理上接不上網路。',
      features: [
        ['零 INTERNET 權限', 'Android manifest 完全不宣告 INTERNET 權限。就算被惡意呼叫，Vault 也接不出去。'],
        ['TEE / DRM 封存種子', '裝置種子錨定在硬體背書的 Keystore TEE / DRM，而不是任何程式都能讀取的檔案。'],
        ['只簽名、不儲存', '身分簽章按需產生，透過已簽署的 IPC 回呼委派給永遠在線的 Engine。'],
        ['零出口', '除非你核准一筆簽名，否則什麼都出不了裝置；沒有值得被外洩的東西。']
      ]
    }
  },
  engine: {
    name: 'Engine',
    icon: B('assets/icon-engine.svg'),
    tag: '聲音 · 端到端加密社交',
    version: 'v3.82.2',
    code: '116',
    url: 'https://github.com/eneatlnc-cell/Spark/releases/download/v3.82.2/Engine-3.82.2-release.apk',
    shy: '線上社交',
    blurb: '你的加密社交客戶端——聊天、群組與身分，全部端到端加密，全部交由離線的 Vault 簽名。',
    features: [
      ['端到端聊天', 'ECDH + AES-256-GCM，AAD 繫結防重放，開放審計函式庫。'],
      ['純記憶體', '無 Room、無 SQLite、無 DataStore——殺掉它就此蒸發。'],
      ['無狀態中繼', '中繼只轉發密文；就算被攻破，得到的也只有雜訊。']
    ],
    stats: [
      ['0', '機內私鑰'],
      ['100%', 'Kotlin · Jetpack Compose'],
      ['200', '單群組成員上限'],
      ['48KB', '單則訊息媒體上限']
    ],
    why: {
      kicker: '為何不同',
      title: ['典型加密 IM 對照', '實體隔離的組合'],
      sub: '多數加密聊天把身分金鑰與訊息托管在一起。Engine 留下的是不同的外洩形狀：除了雜訊，什麼都沒有。',
      features: [
        ['端到端聊天', 'ECDH 協商 + AES-256-GCM，天然綁定防重放，全部由開放審計函式庫支援。'],
        ['群組與門禁', '最多 200 名成員、邀請碼與審核佇列——無需偷看的伺服器，也能做到管制。'],
        ['純記憶體', '無 Room、無 SQLite、無 DataStore。殺掉程式，一切就此蒸發。'],
        ['Spark 經濟', '燃料補助 SPARK 與表情打賞，讓真實經濟在完全不依賴鏈上運作。']
      ]
    }
  }
}

export const ORDER = ['vault', 'engine']

/* ---- 手機截屏演示（純 CSS 模擬畫面）---- */
export const CHAT = {
  title: 'Spark 內部羣組',
  sub: '5 名成員 · 端到端加密',
  msgs: [
    { from: 'them', who: '阿哲', text: '下午的治理投票，金鑰都簽好了嗎？' },
    { from: 'me', text: '簽好了。Vault 離線簽名，Engine 只負責送出密文。' },
    { from: 'them', who: '小魚', text: '伺服器那邊看到的全是雜訊 🔒' },
    { sys: '此對話由 Engine3.0 加密 · Vault 離線簽名' }
  ]
}

export const VAULT_KEYS = [
  { name: '身分金鑰', fp: 'A4:9F:2C:71:08:DD:3E:5B', note: '永不出機' },
  { name: '簽名授權', fp: 'E2:17:88:0C:44:F9:1D:A6', note: '僅限 Engine 呼叫' }
]

export const SIGN_REQ = { from: 'Engine', what: '身分簽章 ×1', when: '剛剛' }

export const LOOP = [
  ['Spark 迴路 — 完整網站', 'https://eneatlnc-cell.github.io/Spark/'],
  ['Engine3.0 — 審計函式庫', 'https://github.com/eneatlnc-cell/Engine3.0'],
  ['Aether — L2 治理', 'https://github.com/eneatlnc-cell/Aether'],
  ['Havix — L0 身分', 'https://github.com/eneatlnc-cell/Havix']
]

export const FOOT = {
  desc: 'Spark 迴路公開的前門。這是最簡單的故事；完整的迴路在另一個站。',
  license: `Apache-2.0 · © 2026 eneatlnc-cell · Engine v3.82.2 · Vault v3.78.0`
}